import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ntpd.java
 *
 * Created on 19 Nov, 2017, 10:32:30 PM
 */

/**
 *
 * @author HP
 */
public class Ntpd extends javax.swing.JFrame {

    /** Creates new form Ntpd */
    public Ntpd() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        a1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jButton7.setText("jbutton6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 560));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        a1.setColumns(20);
        a1.setRows(5);
        jScrollPane1.setViewportView(a1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 550, 190);

        jButton1.setText("Copy(#)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 70, 80, 30);

        jButton2.setText("Reverse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 70, 90, 30);

        jButton3.setText("Italics");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 70, 70, 30);

        jButton4.setText("Bold");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 70, 60, 30);

        jButton5.setText("Set size");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 180, 100, 23);

        jLabel1.setText("Font size");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 70, 14);

        t1.setText("12");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(90, 180, 200, 20);

        jButton6.setText("HOME");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(460, 60, 100, 50);

        jLabel2.setText("Font Color");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 130, 60, 14);

        jButton8.setText("Red");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(80, 130, 70, 23);

        jButton9.setText("Blue");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(150, 130, 80, 23);

        jButton10.setText("Green");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(230, 130, 70, 23);

        jButton11.setText("Pink");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(300, 130, 70, 23);

        jButton12.setText("Black");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(370, 130, 70, 23);

        jButton14.setText("Plain");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(10, 70, 70, 30);

        jButton15.setText("Case");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(380, 70, 70, 30);

        jButton16.setText(" SAVE(#)");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(460, 110, 100, 50);

        jButton17.setText("LOAD(#)");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(460, 160, 100, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Welcome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 30, 70, 17);

        f1.setEditable(false);
        f1.setFont(new java.awt.Font("Tahoma", 1, 12));
        f1.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(f1);
        f1.setBounds(230, 20, 150, 30);

        jLabel4.setText("<html><ul># Only the content can be saved, retrieved or copied.</ul>\n<ul>   Changes like font color, Bold, etc are not permanent.</ul></html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 420, 320, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int q = Integer.parseInt(t1.getText());
String s = a1.getText();
Font v = a1.getFont();
Font y = new Font(s,v.ITALIC,q);
a1.setFont(y);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s = a1.getText();
try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aryan","worldinmyfist","aryanaryan");
    Statement stmt = con.createStatement();
    String query = "INSERT INTO clipb VALUES('"+s+"');";
    stmt.executeUpdate(query);

stmt.close();
con.close();
}


catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
StringBuffer s = new StringBuffer(a1.getText());
StringBuffer d = s.reverse();
a1.setText(""+d);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int q = Integer.parseInt(t1.getText());
String s = a1.getText();
Font v = a1.getFont();
Font y = new Font(s,v.BOLD,q);
a1.setFont(y);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String g = t1.getText().trim();
if(g.equals("")){
JOptionPane.showMessageDialog(null,"No size specified");
}
else{
int y = 0;
y = Integer.parseInt(t1.getText());
String s = a1.getText();
Font v = a1.getFont();
Font u = new Font(s,v.PLAIN,y);
a1.setFont(u);
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Apps d = new Apps();
d.setVisible(true);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.a1.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
this.a1.setForeground(Color.blue);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
this.a1.setForeground(Color.green);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
this.a1.setForeground(Color.pink);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
this.a1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
int q = Integer.parseInt(t1.getText());
String s = a1.getText();
Font v = a1.getFont();
Font y = new Font(s,v.PLAIN,q);
a1.setFont(y);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
String a = a1.getText();
String b = a.toLowerCase();
String c,d;
String e = "";
char f,g;
int h;
int i = a.length();
for(h=0;h<i;h++){
    f = a.charAt(h);
    g = b.charAt(h);
    if(f==g){
        c = "";
        c = c+f;
        d = c.toUpperCase();
        e = e+d;
    }
    else{
        e = e+g;
    }
}
a1.setText(""+e);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aryan","worldinmyfist","aryanaryan");
    Statement stmt = con.createStatement();
    String query = "INSERT INTO doct VALUES('"+a1.getText()+"','"+f1.getText()+"');";
    stmt.executeUpdate(query);

stmt.close();
con.close();
}


catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aryan","worldinmyfist","aryanaryan");
    Statement stmt = con.createStatement();
    String query = "SELECT * FROM colln";
    ResultSet rs = stmt.executeQuery(query);

while(rs.next()){
String b = rs.getString(1);
f1.setText(""+b);
}

stmt.close();
con.close();
rs.close();
}


catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aryan","worldinmyfist","aryanaryan");
    Statement stmt = con.createStatement();
    String query = "SELECT archive FROM doct WHERE emp LIKE '"+f1.getText()+"';";
    ResultSet rs = stmt.executeQuery(query);

while(rs.next()){
String b = rs.getString(1);
a1.setText(""+b);
}

stmt.close();
con.close();
rs.close();
}


catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ntpd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a1;
    private javax.swing.JTextField f1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
